### ISSUE TITLE
Would appreciate acknowledgement

### ISSUE THREAD

**Issue by jakubfiala** [alapini/graphql-to-jsonschema#1]
Hi @alapini, I noticed you recently forked my npm package, [graphql-json-schema](https://github.com/jakubfiala/graphql-json-schema), then removed the fork and created this repository, which seems to have all my code. The only change I noticed is a commented-out `fs.writeFile` and a line in the README stating this is compatible with a certain react module.

I published `graphql-json-schema` under a MIT license so you're free to publish your own version of it, but in the spirit of open source software I'd appreciate if you acknowledged the code was originally written by me.

Alternatively, if there are features you were missing in `graphql-json-schema` (for instance, features that would make it compatible with `react-jsonschema-form`), you could always submit a pull request or just an issue to my package. That way there wouldn't now be two npm packages doing exactly the same thing, and I'd be more than happy to add you as contributor to `react-jsonschema-form`.

Hope that makes sense, happy holidays!

**Comment by alapini** [comment]
Hi @jakubfiala, thanks for the notification.
And sorry for the  'non-acknowledgement', I'll mention you in the README as the initial author of the code.

The issue I was facing with your repo is not a lack of features, but a compatiliby issue.
In fact, your output seems to be `json-schema` specs compilant. But not compatible with  `mozilla-services/react-jsonschema-form` especially on how a reference to a non scalar type is transformed.
In your code, you use a `allOf` wrapper around these properties. In my version, I transform the properties the same way scalar properties are transformed, adding a `$ref` to specify the Reference.
You can see the transform.js, the README and the test files are modified that way.

I'm using this package in just one private project. If you think theses changes could be merged in your repo, I can send a PR and close this one.

**Comment by jakubfiala** [comment]
Thanks a lot for the acknowledgement and explanation @alapini! I'm totally happy for you to develop this package separately. I might even add a note to my readme linking to your package if people need compatibility with `react-jsonschema-form`. Going to close this issue.
